# Generated by Django 2.2 on 2020-09-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200916_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-updated', '-publish_date', '-timestamp']},
        ),
    ]
